replicaCount: 1
image:
  repository: boutiqueacrshared.azurecr.io/frontend
  tag: "latest"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: boutique.local
      paths:
        - path: /
          pathType: Prefix
