apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boutique-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - boutique
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
