apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: auth-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: AuthAlerts
      rules:
        - alert: HighTraffic
          expr: sum(rate(http_requests_total[1m])) > 10
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High Traffic Detected"
            description: "The application is receiving more than 10 requests per second across all services."
