apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boutique-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: boutique-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: POSTGRES_PASSWORD
    - secretKey: AUTH_DB_URL
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: AUTH_DB_URL
    - secretKey: PRODUCTS_DB_URL
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: PRODUCTS_DB_URL
    - secretKey: ORDERS_DB_URL
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: ORDERS_DB_URL
    - secretKey: USERS_DB_URL
      remoteRef:
        key: boutique-dev-eks-db-secret-v3
        property: USERS_DB_URL
