[sonarqube]
# Replace this with the Azure sonarqube_public_ip output from Terraform
<azure_sonarqube_public_ip> ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/id_rsa
# The IP address of the EC2 instance will be injected here or provided dynamically.
# example: 1.2.3.4
