apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boutique-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: boutique-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: boutique-db-secret
        property: POSTGRES_HOST
    - secretKey: POSTGRES_DB
      remoteRef:
        key: boutique-db-secret
        property: POSTGRES_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: boutique-db-secret
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: boutique-db-secret
        property: POSTGRES_PASSWORD
    - secretKey: AUTH_DB_URL
      remoteRef:
        key: boutique-db-secret
        property: AUTH_DB_URL
    - secretKey: PRODUCTS_DB_URL
      remoteRef:
        key: boutique-db-secret
        property: PRODUCTS_DB_URL
    - secretKey: ORDERS_DB_URL
      remoteRef:
        key: boutique-db-secret
        property: ORDERS_DB_URL
    - secretKey: USERS_DB_URL
      remoteRef:
        key: boutique-db-secret
        property: USERS_DB_URL
