apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nishadZC/boutique-capstone-project'
    targetRevision: main
    path: gitops/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boutique-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
