apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 368763425814.dkr.ecr.us-east-1.amazonaws.com/product-service:2be9395d8c5d88d2d05a45bb94f8a7f62f15b1f3
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: PRODUCTS_DB_URL

---

apiVersion: v1
kind: Service
metadata:
  name: product-service

spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      name: http
      port: 3003
      targetPort: 3003
  type: ClusterIP
